# Generated by Django 4.2.6 on 2023-11-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_subscriber_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='post',
        ),
    ]
